#!/bin/bash

# Line to add to .bashrc
line_to_add='export PYTHONPATH="/home/tbrosnan/sims/simfred:$PYTHONPATH"'

# Check if the line already exists in .bashrc
if ! grep -Fxq "$line_to_add" ~/.bashrc; then
    # If not, add the line to the end of .bashrc
    echo "$line_to_add" >> ~/.bashrc
    echo "Line added to .bashrc: $line_to_add"
else
    echo "Line already exists in .bashrc: $line_to_add"
fi

. ~/.bashrc

apt-get install bc


