#!/bin/bash
mkdir sims
cd sims

git clone https://github.com/hqiu-nju/simfred
git clone https://github.com/hqiu-nju/CRAFT-ICS-pipeline

cd ..
# Line to add to .bashrc
dir=$(pwd)
line_to_add="export PYTHONPATH=\"${dir}/sims/simfred:\$PYTHONPATH\""

# Check if the line already exists in .bashrc
if ! grep -Fxq "$line_to_add" ~/.bashrc; then
    # If not, add the line to the end of .bashrc
    echo "$line_to_add" >> ~/.bashrc
    echo "Line added to .bashrc: $line_to_add"
else    
    echo "Line already exists in .bashrc: $line_to_add"
fi

. ~/.bashrc

apt-get install bc


